name: Build Miku UI (Vampire_v3)

on:
  workflow_dispatch:
    branches: [ main ]

env:
  CCACHE_DIR: /tmp/ccache
  USE_CCACHE: 1
  SWAP_SIZE: 8G
  REPO_DEPTH: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 380  # Прямое значение вместо переменной

    steps:
      # 1. Очистка диска и настройка окружения
      - name: Setup environment and clean disk
        run: |
          # Очистка диска
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android/
          sudo rm -rf /var/lib/apt/lists/*
          
          # Настройка swap
          sudo fallocate -l $SWAP_SIZE /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          
          # Установка зависимостей
          sudo apt-get update -y
          sudo apt-get install -y \
            ccache git-core python3 python-is-python3 \
            libssl-dev libncurses5-dev curl openssh-client \
            bc bison flex zip unzip lzop pkg-config
          
          df -h

      # 2. Установка repo
      - name: Install repo
        run: |
          sudo curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo
          repo --version

      # 3. Уведомление о начале
      - name: Telegram notification (start)
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🏗️ *Сборка начата*
            ▫️ *Версия:* Vampire_v3
            ▫️ *Устройство:* blossom
            ▫️ *Время:* $(date +'%Y-%m-%d %H:%M:%S')
            ▫️ *Ссылка:* [GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          parse_mode: markdown

      # 4. Инициализация репозитория
      - name: Initialize repo
        run: |
          git config --global user.name "Edmond2007"
          git config --global user.email "edmondseropyan6@gmail.com"
          
          repo init \
            -u https://github.com/Miku-UI/manifesto \
            -b Vampire_v3 \
            --depth=$REPO_DEPTH \
            --partial-clone \
            --clone-filter=blob:limit=5M || exit 1

      # 5. Синхронизация кода
      - name: Sync code
        run: |
          repo sync \
            -c \
            -j2 \
            --force-sync \
            --no-clone-bundle \
            --no-tags \
            --optimized-fetch \
            --current-branch || exit 1
          
          repo forall -c 'git gc --aggressive'
          df -h

      # 6. Применение device tree
      - name: Apply device trees
        run: |
          git clone \
            --depth=1 \
            --filter=blob:limit=5M \
            https://github.com/Edmond2007/android_device_xiaomi_blossom_local_manifests.git \
            .repo/local_manifests || exit 1
          
          repo sync -c -j2 --fail-fast || exit 1

      # 7. Сборка
      - name: Build ROM
        run: |
          export CCACHE_COMPRESS=1
          ccache -M 30G
          ccache -s
          
          source build/envsetup.sh || exit 1
          lunch miku_blossom-userdebug || exit 1
          mka bacon -j$(($(nproc --all) - 2)) || exit 1

      # 8. Уведомление об успехе
      - name: Telegram notification (success)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ *Сборка успешна!*
            ▫️ *Версия:* Vampire_v3
            ▫️ *Устройство:* blossom
            ▫️ *Артефакты:* [Download](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          parse_mode: markdown

      # 9. Загрузка артефактов
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Miku-UI-Vampire_v3-${{ github.run_number }}
          path: out/target/product/blossom/*.zip
          retention-days: 3

      # 10. Уведомление о неудаче
      - name: Telegram notification (failure)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ *Сборка провалена!*
            ▫️ *Лог:* [View](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          parse_mode: markdown

      # 11. Очистка
      - name: Cleanup
        if: always()
        run: |
          sudo swapoff /swapfile || true
          sudo rm -f /swapfile || true
          ccache -s
