name: Build Miku UI (Vampire_v3) - Fixed

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CCACHE_DIR: /tmp/ccache
  USE_CCACHE: 1
  SWAP_SIZE: 6G
  REPO_URL: "https://storage.googleapis.com/git-repo-downloads/repo"
  PATH: ${{ env.HOME }}/bin:${{ env.PATH }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Set up SWAP
        run: |
          sudo fallocate -l ${{ env.SWAP_SIZE }} /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            ccache \
            git-core \
            python3 \
            python-is-python3 \
            libssl-dev \
            curl \
            openssh-client

      - name: Install repo tool (fixed)
        run: |
          mkdir -p ~/bin
          curl -s ${{ env.REPO_URL }} > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
          which repo  # Проверка установки

      - name: Initialize Miku UI
        run: |
          repo init -u https://github.com/Miku-UI/manifesto -b Vampire_v3
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Apply device trees
        run: |
          git clone https://github.com/Edmond2007/android_device_xiaomi_blossom_local_manifests.git .repo/local_manifests
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Build ROM
        run: |
          ccache -M 50G
          source build/envsetup.sh
          lunch miku_blossom-userdebug
          mka bacon -j$(($(nproc --all) - 1))

      - name: Clean up SWAP
        if: always()
        run: |
          sudo swapoff /swapfile || true
          sudo rm -f /swapfile || true

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: Miku-UI-Vampire_v3-blossom
          path: out/target/product/blossom/*.zip
