name: Build Miku UI (Vampire_v3)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CCACHE_DIR: /tmp/ccache
  USE_CCACHE: 1
  SWAP_SIZE: 10G
  REPO_URL: "https://storage.googleapis.com/git-repo-downloads/repo"
  BUILD_TIME: $(date +'%Y-%m-%d %H:%M:%S')

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      # 1. Настройка окружения
      - name: Setup environment
        run: |
          sudo fallocate -l $SWAP_SIZE /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          
          sudo apt-get update -y
          sudo apt-get install -y \
            ccache git-core python3 \
            python-is-python3 libssl-dev \
            curl openssh-client bc bison flex

      # 2. Установка repo
      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl -s $REPO_URL > ~/bin/repo
          chmod +x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
          ~/bin/repo version

      # 3. Инициализация репозитория
      - name: Initialize repo
        run: |
          git config --global user.name "Edmond2007"
          git config --global user.email "edmondseropyan6@gmail.com"
          ~/bin/repo init -u https://github.com/Miku-UI/manifest -b Vampire_v3

      # 4. Синхронизация кода
      - name: Sync code
        run: |
          ~/bin/repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle

      # 5. Сборка прошивки
      - name: Build ROM
        run: |
          export CCACHE_COMPRESS=1
          ccache -M 50G
          source build/envsetup.sh
          lunch miku_blossom-userdebug
          mka bacon -j$(($(nproc --all) - 1))

      # 6. Уведомление в Telegram (успех)
      - name: Notify Telegram (Success)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ *Сборка завершена успешно!*
            ▫️ *Прошивка:* Miku UI Vampire_v3
            ▫️ *Устройство:* Redmi 9C NFC (blossom)
            ▫️ *Время сборки:* ${{ env.BUILD_TIME }}
            ▫️ *Длительность:* ${{ github.job.status }} минут
            ▫️ *Артефакты:* [Download](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      # 7. Уведомление в Telegram (ошибка)
      - name: Notify Telegram (Failure)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ *Сборка завершена с ошибкой!*
            ▫️ *Прошивка:* Miku UI Vampire_v3
            ▫️ *Устройство:* Redmi 9C NFC (blossom)
            ▫️ *Время сборки:* ${{ env.BUILD_TIME }}
            ▫️ *Логи:* [View](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      # 8. Загрузка артефактов
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Miku-UI-Vampire_v3
          path: out/target/product/blossom/*.zip

      # 9. Очистка
      - name: Cleanup
        if: always()
        run: |
          sudo swapoff /swapfile || true
          sudo rm -f /swapfile || true
