name: Build Miku UI (Vampire_v3)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CCACHE_DIR: /tmp/ccache
  USE_CCACHE: 1
  SWAP_SIZE: 8G

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 400

    steps:
      # 1. Настройка окружения
      - name: Setup environment
        run: |
          sudo fallocate -l $SWAP_SIZE /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h
          
          sudo apt-get update -y
          sudo apt-get install -y \
            ccache git-core python3 python-is-python3 \
            libssl-dev libncurses5-dev curl openssh-client \
            bc bison flex zip unzip lzop pkg-config

      # 2. Установка repo (системная)
      - name: Install repo system-wide
        run: |
          sudo curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo
          repo --version

      # 3. Уведомление о начале сборки
      - name: Telegram Build Start
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 *Сборка запущена*
            ▫️ *Прошивка:* Miku UI Vampire_v3
            ▫️ *Устройство:* Redmi 9C NFC (blossom)
            ▫️ *Запущено:* $(date -u +"%Y-%m-%dT%H:%M:%SZ")
            ▫️ *Ссылка:* [View](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          parse_mode: markdown

      # 4. Инициализация репозитория
      - name: Initialize repo
        run: |
          git config --global user.name "Edmond2007"
          git config --global user.email "edmondseropyan6@gmail.com"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          repo init \
            -u https://github.com/Miku-UI/manifesto \
            -b Vampire_v3 \
            --depth=1 || { echo "Repo init failed"; exit 1; }

      # 5. Синхронизация кода
      - name: Sync code
        run: |
          repo sync \
            -c \
            -j$(($(nproc --all) / 2)) \
            --force-sync \
            --no-clone-bundle \
            --no-tags \
            --optimized-fetch || { echo "Repo sync failed"; exit 1; }

      # 6. Применение device tree
      - name: Apply device trees
        run: |
          git clone \
            --depth=1 \
            https://github.com/Edmond2007/android_device_xiaomi_blossom_local_manifests.git \
            .repo/local_manifests || { echo "Cloning device trees failed"; exit 1; }
          
          repo sync \
            -c \
            -j$(($(nproc --all) / 2)) \
            --fail-fast || { echo "Final repo sync failed"; exit 1; }

      # 7. Засекаем время начала сборки
      - name: Start timer
        id: timer
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      # 8. Сборка прошивки
      - name: Build ROM
        run: |
          export CCACHE_COMPRESS=1
          ccache -M 50G
          ccache -s
          
          source build/envsetup.sh || { echo "Env setup failed"; exit 1; }
          lunch miku_blossom-userdebug || { echo "Lunch failed"; exit 1; }
          mka bacon -j$(($(nproc --all) - 2)) || { echo "Build failed"; exit 1; }

      # 9. Вычисляем длительность сборки
      - name: Calculate duration
        id: duration
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - ${{ env.START_TIME }}))
          echo "DURATION_MIN=$((DURATION / 60))" >> $GITHUB_ENV
          echo "DURATION_SEC=$((DURATION % 60))" >> $GITHUB_ENV

      # 10. Уведомление о результате
      - name: Telegram Build Result
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event_name == 'workflow_dispatch' && '🚀 *Ручная сборка*' || '🚀 *Автоматическая сборка*' }}
            ${{ success() && '✅ *Сборка успешна*' || failure() && '❌ *Сборка провалена*' || '⚠️ *Неизвестный статус*' }}
            ▫️ *Прошивка:* Miku UI Vampire_v3
            ▫️ *Устройство:* blossom
            ▫️ *Длительность:* ${{ env.DURATION_MIN }} мин. ${{ env.DURATION_SEC }} сек.
            ▫️ *Результат:* [${{ job.status }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ${{ success() && '▫️ *Артефакты:* [Download](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})' || '' }}
          parse_mode: markdown

      # 11. Загрузка артефактов
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Miku-UI-Vampire_v3-${{ github.run_number }}
          path: out/target/product/blossom/*.zip
          retention-days: 3

      # 12. Очистка
      - name: Cleanup
        if: always()
        run: |
          sudo swapoff /swapfile || true
          sudo rm -f /swapfile || true
          ccache -s
