name: Build Miku UI (Vampire_v3)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CCACHE_DIR: /tmp/ccache
  USE_CCACHE: 1
  SWAP_SIZE: 16G
  REPO_DEPTH: 1
  BUILD_TIMEOUT: 380  # минуты

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.BUILD_TIMEOUT }}

    steps:
      # 1. Очистка диска и настройка окружения
      - name: Setup environment and clean disk
        run: |
          # Очистка диска
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android/
          sudo rm -rf /var/lib/apt/lists/*
          
          # Настройка swap
          sudo fallocate -l $SWAP_SIZE /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          
          # Установка зависимостей
          sudo apt-get update -y
          sudo apt-get install -y \
            ccache git-core python3 python-is-python3 \
            libssl-dev libncurses5-dev curl openssh-client \
            bc bison flex zip unzip lzop pkg-config
          
          df -h

      # 2. Установка repo
      - name: Install repo
        run: |
          sudo curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo
          repo --version

      # 3. Уведомление о начале
      - name: Telegram notification (start)
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🏗️ *Сборка начата*
            ▫️ *Версия:* Vampire_v3
            ▫️ *Устройство:* blossom
            ▫️ *Время:* $(date +'%Y-%m-%d %H:%M:%S')
            ▫️ *Ссылка:* [GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          parse_mode: markdown

      # 4. Инициализация репозитория с проверкой ошибок
      - name: Initialize repo
        id: init_repo
        run: |
          git config --global user.name "Edmond2007"
          git config --global user.email "edmondseropyan6@gmail.com"
          
          repo init \
            -u https://github.com/Miku-UI/manifesto \
            -b Vampire_v3 \
            --depth=${{ env.REPO_DEPTH }} \
            --partial-clone \
            --clone-filter=blob:limit=5M
          
          if [ $? -ne 0 ]; then
            echo "::error::Repo init failed"
            exit 1
          fi

      # 5. Синхронизация кода с контролем места
      - name: Sync code
        id: sync_code
        run: |
          # Проверка свободного места перед синхронизацией
          FREE_SPACE=$(df -h / | awk 'NR==2 {print $4}')
          echo "Free space before sync: $FREE_SPACE"
          
          repo sync \
            -c \
            -j$(nproc - 2) \  # Уменьшенное количество потоков
            --force-sync \
            --no-clone-bundle \
            --no-tags \
            --optimized-fetch \
            --current-branch
          
          SYNC_STATUS=$?
          
          # Очистка после синхронизации
          repo forall -c 'git gc --aggressive'
          
          if [ $SYNC_STATUS -ne 0 ]; then
            echo "::error::Repo sync failed"
            exit 1
          fi

          df -h

      # 6. Применение device tree
      - name: Apply device trees
        id: apply_trees
        run: |
          git clone \
            --depth=1 \
            --filter=blob:limit=5M \
            https://github.com/Edmond2007/android_device_xiaomi_blossom_local_manifests.git \
            .repo/local_manifests
          
          if [ $? -ne 0 ]; then
            echo "::error::Failed to clone device trees"
            exit 1
          fi
          
          repo sync -c -j2 --fail-fast
          if [ $? -ne 0 ]; then
            echo "::error::Final sync failed"
            exit 1
          fi

      # 7. Сборка с контролем памяти
      - name: Build ROM
        id: build_rom
        run: |
          # Лимиты для сборки
          export CCACHE_COMPRESS=1
          ccache -M 30G  # Уменьшенный кеш
          ccache -s
          
          source build/envsetup.sh || exit 1
          lunch miku_blossom-userdebug || exit 1
          
          # Сборка с мониторингом места
          while true; do
            free -h
            df -h /
            mka bacon -j$(($(nproc --all) - 2)) && break
            
            # Если сборка упала из-за нехватки места
            if [ $(df / --output=pcent | tail -1 | tr -dc '0-9') -gt 90 ]; then
              echo "::warning::Low disk space, cleaning..."
              repo forall -c 'git gc --aggressive'
              ccache -c
              rm -rf out/target/product/*/obj/EXECUTABLES
            else
              exit 1
            fi
          done

      # 8. Уведомление об успехе
      - name: Telegram notification (success)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ *Сборка успешна!*
            ▫️ *Версия:* Vampire_v3
            ▫️ *Устройство:* blossom
            ▫️ *Время сборки:* ${{ steps.duration.outputs.time }}
            ▫️ *Артефакты:* [Download](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          parse_mode: markdown

      # 9. Загрузка артефактов
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Miku-UI-Vampire_v3-${{ github.run_number }}
          path: out/target/product/blossom/*.zip
          retention-days: 3

      # 10. Уведомление о неудаче
      - name: Telegram notification (failure)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ *Сборка провалена!*
            ▫️ *Этап:* ${{ steps.check_failure.outputs.failed_step }}
            ▫️ *Лог:* [View](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ▫️ *Время выполнения:* ${{ steps.duration.outputs.time }}
          parse_mode: markdown

      # 11. Определение причины падения
      - name: Check failure reason
        if: failure()
        id: check_failure
        run: |
          if [[ "${{ steps.init_repo.outcome }}" == 'failure' ]]; then
            echo "failed_step=Инициализация репозитория" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.sync_code.outcome }}" == 'failure' ]]; then
            echo "failed_step=Синхронизация кода" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.apply_trees.outcome }}" == 'failure' ]]; then
            echo "failed_step=Применение device tree" >> $GITHUB_OUTPUT
          else
            echo "failed_step=Сборка прошивки" >> $GITHUB_OUTPUT
          fi

      # 12. Расчет времени
      - name: Calculate duration
        id: duration
        run: |
          START=${{ job.steps[*].startTime }}
          END=$(date -u +%s)
          DURATION=$((END - START))
          HOURS=$((DURATION / 3600))
          MINUTES=$(( (DURATION % 3600) / 60 ))
          echo "time=${HOURS}ч ${MINUTES}м" >> $GITHUB_OUTPUT

      # 13. Очистка
      - name: Cleanup
        if: always()
        run: |
          sudo swapoff /swapfile || true
          sudo rm -f /swapfile || true
          ccache -s
