name: Build Miku UI (Vampire_v3)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CCACHE_DIR: /tmp/ccache
  USE_CCACHE: 1
  CCACHE_COMPRESS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # Полная история для repo

      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            ccache \
            git-core \
            python3 \
            python3-pip \
            libssl-dev \
            libncurses5-dev \
            bc \
            bison \
            flex \
            zip \
            unzip \
            rsync \
            curl \
            zlib1g-dev \
            gcc-multilib \
            g++-multilib

      - name: Set up repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize Miku UI (Vampire_v3)
        run: |
          repo init -u https://github.com/Miku-UI/manifesto -b Vampire_v3 --git-lfs --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune

      - name: Apply device trees
        run: |
          git clone https://github.com/Edmond2007/android_device_xiaomi_blossom_local_manifests.git -b main .repo/local_manifests
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune

      - name: Set up ccache
        uses: actions/cache@v3
        with:
          path: /tmp/ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('.repo/manifest.xml') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Build ROM
        run: |
          ccache -M 50G
          source build/envsetup.sh
          lunch miku_blossom-userdebug
          mka bacon -j$(($(nproc --all) - 1))  # Оставляем 1 ядро свободным

      - name: Upload ROM
        uses: actions/upload-artifact@v3
        with:
          name: Miku-UI-Vampire_v3-blossom-$(date +%Y%m%d)
          path: |
            out/target/product/blossom/*.zip
            out/target/product/blossom/*.md5sum
          retention-days: 31
