
name: Build Miku UI (Vampire_v3) - Valid

on:
  workflow_dispatch:

env:
  CCACHE_DIR: /tmp/ccache
  USE_CCACHE: 1
  SWAP_SIZE: 6G
  REPO_URL: "https://storage.googleapis.com/git-repo-downloads/repo"
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Set up SWAP
        run: |
          sudo fallocate -l ${{ env.SWAP_SIZE }} /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y             ccache             git             python3             python-is-python3             libssl-dev             curl             jq             openssh-client

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl -s ${{ env.REPO_URL }} > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize Miku UI source
        run: |
          repo init -u https://github.com/Miku-UI/manifesto -b Vampire_v3
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags

      - name: Clone device trees
        run: |
          git clone https://github.com/Edmond2007/android_device_xiaomi_blossom_local_manifests.git .repo/local_manifests
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags

      - name: Build ROM
        run: |
          ccache -M 50G
          source build/envsetup.sh
          lunch miku_blossom-userdebug
          mka bacon -j4

      - name: Clean up SWAP
        if: always()
        run: |
          sudo swapoff /swapfile || true
          sudo rm -f /swapfile || true

      - name: Upload to Telegram
        if: success()
        run: |
          ZIP_FILE=$(find out/target/product/blossom -name "*.zip" | head -n1)
          curl -F chat_id="$TELEGRAM_CHAT_ID"                -F document=@"$ZIP_FILE"                -F caption="✅ Miku UI build completed."                https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument
