name: Sync Miku UI Repo

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y curl python-is-python3
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Init Miku UI repo (branch: Vampire_v3)
        run: |
          repo init -u https://github.com/Miku-UI/manifesto -b Vampire_v3 --depth=1
          git clone -b lineage-22.2 https://github.com/Edmond2007/android_device_xiaomi_blossom_local_manifests .repo/local_manifests

      - name: Sync repo
        run: repo sync -c --no-tags --no-clone-bundle -j8

      - name: Clean unnecessary .git folders
        run: |
          find .repo/projects/ -type d -name ".git" | xargs rm -rf
          find .repo/project-objects/ -type d -name ".git" | xargs rm -rf
          rm -rf .repo/manifests.git
          rm -rf .repo/repo/.git

      - name: Compress .repo folder
        run: tar -I 'xz -9' -cf repo.tar.xz .repo

      - name: Upload to GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo
          path: repo.tar.xz

      - name: Send to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -F document=@repo.tar.xz \
               -F chat_id=$TELEGRAM_CHAT_ID \
               -F caption="📦 .repo архив для Miku UI готов" \
               "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument"
